all:
	gcc var_1.c -o var1 
	gcc var_2.c -o var2 
	gcc var_3.c -o var3
	gcc var_4.c -o var4 
	./var1
	./var2
	./var3
	./var4
build:
	gcc var_1.c -o var1 
	gcc var_2.c -o var2 
	gcc var_3.c -o var3
	gcc var_4.c -o var4  

run-var1:
	gcc var_1.c -o var1
	./var1
run-var2:
	gcc var_2.c -o var2
	./var2
run-var3:
	gcc var_3.c -o var3
	./var3
run-var4:
	gcc var_4.c -o var4
	./var4
clean:
	rm -rf var1 var2 var3 var4
